version: '3.8'
 
services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  celery:
    build: .
    command: celery worker -l info -A app.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/app'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'
